CREATE DATABASE resreq_practice

USE resreq_practice

CREATE TABLE dessert (
id INTEGER(11) AUTO_INCREMENT NOT NULL,
name VARCHAR(50) NOT NULL,
description VARCHAR(255) NOT NULL,
price DECIMAL(5,2) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE entre (
id INTEGER(11) AUTO_INCREMENT NOT NULL,
name VARCHAR(50) NOT NULL,
description VARCHAR(255) NOT NULL,
price DECIMAL(5,2) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE appetizer  (
id INTEGER(11) AUTO_INCREMENT NOT NULL,
name VARCHAR(50) NOT NULL,
description VARCHAR(255) NOT NULL,
price DECIMAL(5,2) NOT NULL,
PRIMARY KEY (id)
);